INSERT INTO "usuario" (apellido_paterno, apellido_materno, nombres, correo_electronico, dni, password_hash, fecha_creacion, grado_academico, activo, id_rol) VALUES
('Rivas', 'Puga', 'Abdón', 'abdon.rivas@unsaac.edu.pe', '12345678', 'hashed_password_1', NOW(), 'Licenciado', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Candia', 'Oviedo', 'Dennis Iván', 'dennis.candia@unsaac.edu.pe', '12345679', 'hashed_password_2', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Aguirre', 'Carbajal', 'Doris Sabina', 'doris.aguirre@unsaac.edu.pe', '12345680', 'hashed_password_3', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Carrasco', 'Poblete', 'Edwin', 'edwincarrasco@unsaac.edu.pe', '12345681', 'hashed_password_4', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Cutipa', 'Arapa', 'Efraina Gladys', 'efraina.cutipa@unsaac.edu.pe', '12345682', 'hashed_password_5', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Palomino', 'Olivera', 'Emilio', 'emiliopalomino@unsaac.edu.pe', '12345683', 'hashed_password_6', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Gamarra', 'Saldivar', 'Enrique', 'enrique.gamarra@unsaac.edu.pe', '12345684', 'hashed_password_7', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Pacheco', 'Vasquez', 'Esther Cristina', 'esther.pacheco@unsaac.edu.pe', '12345685', 'hashed_password_8', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Ticona', 'Pari', 'Guzmán', 'guzman.ticona@unsaac.edu.pe', '12345686', 'hashed_password_9', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Vera', 'Olivera', 'Harley', 'harley.vera@unsaac.edu.pe', '12345687', 'hashed_password_10', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Dueñas', 'De La Cruz', 'Henry Samuel', 'henry.duenas@unsaac.edu.pe', '12345688', 'hashed_password_11', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Castañeda', 'Chirinos', 'Hernán', 'hernan.castaneda@unsaac.edu.pe', '12345689', 'hashed_password_12', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Medrano', 'Valencia', 'Iván Cesar', 'ivan.medrano@unsaac.edu.pe', '12345690', 'hashed_password_13', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Rozas', 'Huacho', 'Javier Arturo', 'javier.rozas@unsaac.edu.pe', '12345691', 'hashed_password_14', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Chávez', 'Centeno', 'Javier David', 'javier.chavez@unsaac.edu.pe', '12345692', 'hashed_password_15', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Pillco', 'Quispe', 'José Mauro', 'jose.pillco@unsaac.edu.pe', '12345693', 'hashed_password_16', NOW(), 'Licenciado', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Carbajal', 'Luna', 'Julio Cesar', 'julio.carbajal@unsaac.edu.pe', '12345694', 'hashed_password_17', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Medina', 'Miranda', 'Karelia', 'karelia.medina@unsaac.edu.pe', '12345695', 'hashed_password_18', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Enciso', 'Rodas', 'Lauro', 'lauro.enciso@unsaac.edu.pe', '12345696', 'hashed_password_19', NOW(), 'Doctor', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Baca', 'Cardenas', 'Lino Aquiles', 'lino.baca@unsaac.edu.pe', '12345697', 'hashed_password_20', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Flores', 'Pacheco', 'Lino Prisciliano', 'lino.flores@unsaac.edu.pe', '12345698', 'hashed_password_21', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Monzón', 'Condori', 'Luis Álvaro', 'luis.monzon@unsaac.edu.pe', '12345699', 'hashed_password_22', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Palma', 'Ttito', 'Luis Beltrán', 'luis.palma@unsaac.edu.pe', '12345700', 'hashed_password_23', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Peñaloza', 'Figueroa', 'Manuel Aurelio', 'manuel.penaloza@unsaac.edu.pe', '12345701', 'hashed_password_24', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Irpanocca', 'Cusimayta', 'Maritza Katherine', 'maritza.irpanocca@unsaac.edu.pe', '12345702', 'hashed_password_25', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Acurio', 'Usca', 'Nila Zonia', 'nila.acurio@unsaac.edu.pe', '12345703', 'hashed_password_26', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Alzamora', 'Paredes', 'Robert Wilbert', 'robert.alzamora@unsaac.edu.pe', '12345704', 'hashed_password_27', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Valdez', 'Sierra', 'Rodrigo', 'rodrigo.valdez@unsaac.edu.pe', '12345705', 'hashed_password_28', NOW(), 'Licenciado', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Meza', 'Chinchay', 'Rosaura', 'rosaura.meza@unsaac.edu.pe', '12345706', 'hashed_password_29', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Chambi', 'Huamán', 'Sergio', 'sergio.chambi@unsaac.edu.pe', '12345707', 'hashed_password_30', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Ticona', 'Cayara', 'Tatiana Tania', 'tatiana.ticona@unsaac.edu.pe', '12345708', 'hashed_password_31', NOW(), 'Ingeniero', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Sanchez', 'Sonia', 'Teresa', 'teresa.sanchez@unsaac.edu.pe', '12345709', 'hashed_password_32', NOW(), 'Licenciado', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Aldana', 'Ormeño', 'Tito', 'tito.aldana@unsaac.edu.pe', '12345710', 'hashed_password_33', NOW(), 'Magister', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente')),
('Salazar', 'Marcano', 'Yudy', 'yudy.salazar@unsaac.edu.pe', '12345711', 'hashed_password_34', NOW(), 'Licenciado', TRUE, (SELECT id_rol FROM rol WHERE nombre_rol = 'Docente'));


INSERT INTO usuario (apellido_paterno, apellido_materno, nombres, correo_electronico, dni, password_hash, fecha_creacion, grado_academico, activo, id_rol) VALUES
('Gutierrez', 'Salazar', 'Juan Manuel', '173891@unsaac.edu.pe', '12345671', 'hashed_password', NOW(), 'Estudiante', TRUE, 2),
('Gutierrez', 'Taqqquere', 'Luis Fernando', '172145@unsaac.edu.pe', '23456782', 'hashed_password', NOW(), 'Estudiante', TRUE, 2),
('Gutierrez', 'Yucra', 'Pamela', '176782@unsaac.edu.pe', '34567893', 'hashed_password', NOW(), 'Estudiante', TRUE, 2),
('Hancco', 'Chaco', 'Jose Maria', '170394@unsaac.edu.pe', '45678904', 'hashed_password', NOW(), 'Estudiante', TRUE, 2),
('Hancco', 'León', 'Alexander', '175643@unsaac.edu.pe', '56789015', 'hashed_password', NOW(), 'Estudiante', TRUE, 2),
('Hanco', 'Gayona', 'Mariela', '174820@unsaac.edu.pe', '67890126', 'hashed_password', NOW(), 'Estudiante', TRUE, 2),
('Hinojosa', 'Huarca', 'Brayan Alexandert', '172917@unsaac.edu.pe', '78901237', 'hashed_password', NOW(), 'Estudiante', TRUE, 2),
('Holguin', 'Condori', 'Julio Josue', '177059@unsaac.edu.pe', '89012348', 'hashed_password', NOW(), 'Estudiante', TRUE, 2),
('Huaman', 'Atayupanqui', 'Lisbet Paola', '178341@unsaac.edu.pe', '90123459', 'hashed_password', NOW(), 'Estudiante', TRUE, 2),
('Huaman', 'Cabrera', 'Yonathan', '171578@unsaac.edu.pe', '01234560', 'hashed_password', NOW(), 'Estudiante', TRUE, 2),
('Huallpa', 'Montalvo', 'Ralexs', '170984@unsaac.edu.pe', '12345672', 'hashed_password', NOW(), 'Estudiante', TRUE, 2);

